safe: false
markdown: redcarpet
pygments: true
base_path: http://grandwazir.github.io/StarterKit
plugin:
  name: StarterKit
  package_name: starter-kit
  bukkit_dev: starterkit
author:
  name: James Richardson
