safe: false
markdown: redcarpet
pygments: true
base_path: "http://grandwazir.github.io/BanHammer"
plugin:
  name: BanHammer
  package_name: ban-hammer
  bukkit_dev: banhammer
author:
  name: James Richardson
